### ISSUE TITLE
How to view chart without pagination?

### ISSUE THREAD

**Issue by atp0303** [mbielanczuk/jQuery.Gantt#20]
Is there a way to render the chart without vertical pagination?   If i had 50 tasks then i want to show all 50 in one page?

**Comment by taitems** [comment]
You can set <code>itemsPerPage: 50</code> but the controls will still be there.

**Comment by atp0303** [comment]
Thanks for that - Just a friendly FYI - the performance is not very good when set to say 25 items per page.  Not sure what the problem is but from what i can tell the bottle neck is not the data or HTTP request.

**Comment by taitems** [comment]
Yeah the performance is very average. I found an issue with Chrome in particular that I fixed in my own branch. Chrome was taking anywhere from 3 to 5 times longer than other browsers including IE9.
