### ISSUE TITLE
Zooming to hours view.

### ISSUE THREAD

**Issue by mbielanczuk** [mbielanczuk/jQuery.Gantt#4]
@Fox
Great code can you have a single day view with time?

@Jack
Great code! Can you change the “row header year” to “row header day” and “row header month” to “row header hour”?

@Marcelo:
I like this very much. But I wonder if there is a simple way to Cutomize hours versus days?
Because I need a time grid of days (line) and hour (column), along with progress bars.

**Comment by janhartmann** [comment]
Great script! I could use month view instead of days. :-) Is this possible? Thank you!

**Comment by mbielanczuk** [comment]
Not yet, but it will be.

**Comment by janhartmann** [comment]
Nice to hear that - I need that to complete a task! :-) Good work so far!

**Comment by loerzing** [comment]
Month- or even year-view, would be great. Great plugin so far!
